app/Http/routes.php
<?php

use App\Http\Controllers\Apps\PermissionManagementController;
use App\Http\Controllers\Apps\RoleManagementController;
use App\Http\Controllers\Apps\UserManagementController;
use App\Http\Controllers\Auth\SocialiteController;
use App\Http\Controllers\DashboardController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['auth', 'verified'])->group(function () {

    Route::get('/', [DashboardController::class, 'index']);

    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

    Route::name('user-management.')->group(function () {
        Route::resource('/user-management/users', UserManagementController::class);
        Route::resource('/user-management/roles', RoleManagementController::class);
        Route::resource('/user-management/permissions', PermissionManagementController::class);
    });

});

Route::get('/error', function () {
    abort(500);
});

Route::get('/auth/redirect/{provider}', [SocialiteController::class, 'redirect']);

require __DIR__ . '/auth.php';


Route::get('generator_builder', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@builder')->name('io_generator_builder');

Route::get('field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@fieldTemplate')->name('io_field_template');

Route::get('relation_field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@relationFieldTemplate')->name('io_relation_field_template');

Route::post('generator_builder/generate', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generate')->name('io_generator_builder_generate');

Route::post('generator_builder/rollback', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@rollback')->name('io_generator_builder_rollback');

Route::post(
    'generator_builder/generate-from-file',
    '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generateFromFile'
)->name('io_generator_builder_generate_from_file');

routes/web.php
<?php

use App\Http\Controllers\Setting\CompanyController;

use App\Http\Controllers\Apps\PermissionManagementController;
use App\Http\Controllers\Apps\RoleManagementController;
use App\Http\Controllers\Apps\UserManagementController;
use App\Http\Controllers\Auth\SocialiteController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\Apps\SignaturePadController;
use Illuminate\Support\Facades\Route;
use \InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController;
use Symfony\Component\HttpFoundation\File\File;




/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/modules/{module}/{type}/{file}', [ function ($module, $type, $file) {

//     return 'aaaa';
// }]);

// Routes accessible only to users with "Super Admin" role
// Route::middleware(['auth', 'superAdmin'])->group(function () {
//     // Your protected routes go here
//     Route::get('/', function () {
//         return 'This is Super Admin';
//     });
// });

// Route::middleware(['auth', 'role:Super Admin'])->group(function () {
//     // Route::get('/', function () {
//     //     return 'This is Super Admin';
//     // });
//     Route::get('/', [DashboardController::class, 'index']);
//     Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
//     Route::resource('logs', App\Http\Controllers\LogController::class);
//     Route::resource('user-infos', App\Http\Controllers\UserInfoController::class);

//     Route::name('user-management.')->group(function () {
//         Route::resource('/user-management/users', UserManagementController::class);
//         Route::resource('/user-management/roles', RoleManagementController::class);
//         Route::resource('/user-management/permissions', PermissionManagementController::class);
//     });
// });

// Route::get('generator_builder', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@builder')->name('io_generator_builder');
// Route::get('generator_builder', [GeneratorBuilderController::class, 'builder'])->name('io_generator_builder');
// Route::get('field_template', [GeneratorBuilderController::class, 'fieldTemplate'])->name('io_field_template');
// Route::get('relation_field_template', [GeneratorBuilderController::class, 'relationFieldTemplate'])->name('io_relation_field_template');
// Route::post('generator_builder/generate', [GeneratorBuilderController::class, 'generate'])->name('io_generator_builder_generate');
// Route::post('generator_builder/generate-from-file', [GeneratorBuilderController::class, 'generateFromFile'])->name('io_generator_builder_generate_from_file');
// Route::post('generator_builder/rollback', [GeneratorBuilderController::class, 'rollback'])->name('io_generator_builder_rollback');

// Route::get('field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@fieldTemplate')->name('io_field_template');

// Route::get('relation_field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@relationFieldTemplate')->name('io_relation_field_template');

// Route::post('generator_builder/generate', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generate')->name('io_generator_builder_generate');

// Route::post('generator_builder/rollback', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@rollback')->name('io_generator_builder_rollback');

// ×Fail! The POST method is not supported for route generator_builder/generate. Supported methods: GET, HEAD.


// Route::post(
//     'generator_builder/generate-from-file',
//     '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generateFromFile'
// )->name('io_generator_builder_generate_from_file');


Route::middleware(['auth'])->group(function () {

    // Route::get('/', [DashboardController::class, 'index']);

    // Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::resource('logs', App\Http\Controllers\LogController::class);
    Route::resource('user-infos', App\Http\Controllers\UserInfoController::class);

    Route::name('user-management.')->group(function () {
        Route::get('/user-management/my-profile', [UserManagementController::class, 'myProfile'])->name('myProfile');
        Route::resource('/user-management/users', UserManagementController::class);
        Route::resource('/user-management/roles', RoleManagementController::class);
        Route::resource('/user-management/permissions', PermissionManagementController::class);

        // API
        Route::prefix('/user-management/api')->group(function () {
            Route::post('/users', [UserManagementController::class, 'saveUser'])->name('postUser');

        });
    });

    Route::name('apps.')->group(function () {
        Route::resource('/apps/signaturepad', SignaturePadController::class);

        // API
        // Route::prefix('/user-management/api')->group(function () {
        //     Route::post('/users', [UserManagementController::class, 'saveUser'])->name('postUser');

        // });
    });

    Route::name('settings.')->group(function () {
        Route::get('/settings', [SettingController::class, 'index'])->name('index');
        Route::get('/image/{disk}/{filename}', [SettingController::class, 'showLogo'])->name('showLogo');

        Route::get('/settings/company', [CompanyController::class, 'index'])->name('company');

        // Route::resource('company', CompanyController::class,[
        //     'as' => 'company'
        // ]);

        // API
        Route::prefix('/setting/api')->group(function () {
            Route::get('/company', [SettingController::class, 'getCompany'])->name('getCompany');
            Route::get('/limit', [SettingController::class, 'getLimit'])->name('getLimit');
            Route::get('/version', [SettingController::class, 'getVersion'])->name('getVersion');
            Route::post('/company', [SettingController::class, 'saveCompany'])->name('postCompany');
            Route::post('/sla', [SettingController::class, 'saveSla'])->name('postSla');
            Route::get('/notification', [SettingController::class, 'getNotification'])->name('getNotification');
            Route::post('/notification', [SettingController::class, 'saveNotification'])->name('postNotification');
            Route::put('/update-company-status/{id}', [SettingController::class, 'updateStatus'])->name('update-company-status');
            // Route::put('/update-company-status/{id}', 'SettingController@updateStatus')->name('update-company-status');
            // Route::post('/company', 'SettingController@saveCompany');

        });

    });

});



Route::get('/clear-cache/{cacheType?}', [SettingController::class, 'clearCache'])
                ->name('clear-cache');

Route::get('/error', function () {
    abort(500);
});

Route::get('/auth/redirect/{provider}', [SocialiteController::class, 'redirect']);

require __DIR__ . '/auth.php';
require __DIR__.'/superadmin.php';
require __DIR__.'/client.php';

// Fallback route
// Route::fallback(function () {
//     return redirect()->back();
// });




Route::resource('user-infos', App\Http\Controllers\UserInfoController::class);

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Storage;
use Laravel\Sanctum\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\Facades\Auth;
use App\Scopes\SuperAdminScope;
use Illuminate\Database\Eloquent\SoftDeletes;
use Ramsey\Uuid\Uuid;
use App\Traits\UuidTrait;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;
    use HasRoles, SoftDeletes;

    // protected $primaryKey = 'id';
    // protected $keyType = 'string';
    // public $incrementing = false;

protected static function boot()
{
    parent::boot();

    // static::creating(function ($model) {
    //     $model->{$model->getKeyName()} = Uuid::uuid4()->toString();
    // });

    if (Auth::check()) {
        static::addGlobalScope(new SuperAdminScope());
    }
}


    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'username',
        'parent_id',
        'account_id',
        'cid',
        'password',
        'last_login_at',
        'last_login_ip',
        'profile_photo_path',
        'level_access',
        'subscription',
        'status',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'last_login_at' => 'datetime',
    ];


    public function getProfilePhotoUrlAttribute()
    {
        if ($this->profile_photo_path) {
            return Storage::url($this->profile_photo_path);
        }

        return $this->profile_photo_path;
    }
}

resources/views/layout/partials/header-layout/header/_navbar.blade.php
<!--begin::Navbar-->
<div class="app-navbar flex-shrink-0">
    {{-- <!--begin::Search-->
    <div class="app-navbar-item align-items-stretch ms-1 ms-md-3">
        @include(config('settings.KT_THEME_LAYOUT_DIR').'/partials/header-layout/search/_dropdown')
    </div>
    <!--end::Search--> --}}
    {{-- <!--begin::Activities-->
    <div class="app-navbar-item ms-1 ms-md-3">
        <!--begin::Drawer toggle-->
        <div class="btn btn-icon btn-custom btn-icon-muted btn-active-light btn-active-color-primary w-30px h-30px w-md-40px h-md-40px" id="kt_activities_toggle">{!! getIcon('chart-simple', 'fs-2 fs-md-1') !!}</div>
        <!--end::Drawer toggle-->
    </div>
    <!--end::Activities--> --}}
    <!--begin::Notifications-->
    {{-- <div class="app-navbar-item ms-1 ms-md-3">
        <!--begin::Menu- wrapper-->
        <div class="btn btn-icon btn-custom btn-icon-muted btn-active-light btn-active-color-primary w-30px h-30px w-md-40px h-md-40px" data-kt-menu-trigger="{default: 'click', lg: 'hover'}" data-kt-menu-attach="parent"
             data-kt-menu-placement="bottom-end" id="kt_menu_item_wow">{!! getIcon('element-plus', 'fs-2 fs-md-1') !!}</div>
        @include('partials/menus/_notifications-menu')
        <!--end::Menu wrapper-->
    </div> --}}
    <!--end::Notifications-->
    <!--begin::Chat-->
    {{-- <div class="app-navbar-item ms-1 ms-md-3">
        <!--begin::Menu wrapper-->
        <div class="btn btn-icon btn-custom btn-icon-muted btn-active-light btn-active-color-primary w-30px h-30px w-md-40px h-md-40px position-relative" id="kt_drawer_chat_toggle">{!! getIcon('message-text-2', 'fs-2 fs-md-1') !!}
            <span class="bullet bullet-dot bg-success h-6px w-6px position-absolute translate-middle top-0 start-50 animation-blink"></span>
        </div>
        <!--end::Menu wrapper-->
    </div> --}}
    <!--end::Chat-->
    <!--begin::My apps links-->
    <div class="app-navbar-item ms-1 ms-md-3">
        <!--begin::Menu wrapper-->
        <div class="btn btn-icon btn-custom btn-icon-muted btn-active-light btn-active-color-primary w-30px h-30px w-md-40px h-md-40px" data-kt-menu-trigger="{default: 'click', lg: 'hover'}" data-kt-menu-attach="parent"
             data-kt-menu-placement="bottom-end">{!! getIcon('element-11', 'fs-2 fs-md-1') !!}</div>
        @include('partials/menus/_my-apps-menu')
        <!--end::Menu wrapper-->
    </div>
    <!--end::My apps links-->
    <!--begin::Theme mode-->
    <div class="app-navbar-item ms-1 ms-md-3">
        @include('partials/theme-mode/_main')
    </div>
    <!--end::Theme mode-->
    <!--begin::User menu-->
    <div class="app-navbar-item ms-1 ms-md-3" id="kt_header_user_menu_toggle">
        <!--begin::Menu wrapper-->
        <div class="cursor-pointer symbol symbol-30px symbol-md-40px" data-kt-menu-trigger="{default: 'click', lg: 'hover'}" data-kt-menu-attach="parent" data-kt-menu-placement="bottom-end">
            @if(Auth::user()->profile_photo_url)
                <img src="{{ \Auth::user()->profile_photo_url }}" alt="user"/>
            @else
                <div class="symbol-label fs-3 {{ app(\App\Actions\GetThemeType::class)->handle('bg-light-? text-?', Auth::user()->name) }}">
                    {{ substr(Auth::user()->name, 0, 1) }}
                </div>
            @endif
        </div>
        @include('partials/menus/_user-account-menu')
        <!--end::Menu wrapper-->
    </div>
    <!--end::User menu-->
    {{-- <!--begin::Header menu toggle-->
    <div class="app-navbar-item d-lg-none ms-2 me-n3" title="Show header menu">
        <div class="btn btn-icon btn-active-color-primary w-30px h-30px w-md-35px h-md-35px" id="kt_app_header_menu_toggle">{!! getIcon('text-align-left', 'fs-2 fs-md-1') !!}</div>
    </div>
    <!--end::Header menu toggle--> --}}
</div>
<!--end::Navbar-->