app/Http/routes.php
<?php

use App\Http\Controllers\Apps\PermissionManagementController;
use App\Http\Controllers\Apps\RoleManagementController;
use App\Http\Controllers\Apps\UserManagementController;
use App\Http\Controllers\Auth\SocialiteController;
use App\Http\Controllers\DashboardController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['auth', 'verified'])->group(function () {

    Route::get('/', [DashboardController::class, 'index']);

    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

    Route::name('user-management.')->group(function () {
        Route::resource('/user-management/users', UserManagementController::class);
        Route::resource('/user-management/roles', RoleManagementController::class);
        Route::resource('/user-management/permissions', PermissionManagementController::class);
    });

});

Route::get('/error', function () {
    abort(500);
});

Route::get('/auth/redirect/{provider}', [SocialiteController::class, 'redirect']);

require __DIR__ . '/auth.php';


Route::get('generator_builder', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@builder')->name('io_generator_builder');

Route::get('field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@fieldTemplate')->name('io_field_template');

Route::get('relation_field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@relationFieldTemplate')->name('io_relation_field_template');

Route::post('generator_builder/generate', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generate')->name('io_generator_builder_generate');

Route::post('generator_builder/rollback', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@rollback')->name('io_generator_builder_rollback');

Route::post(
    'generator_builder/generate-from-file',
    '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generateFromFile'
)->name('io_generator_builder_generate_from_file');

routes/web.php
<?php

use App\Http\Controllers\Setting\CompanyController;

use App\Http\Controllers\Apps\PermissionManagementController;
use App\Http\Controllers\Apps\RoleManagementController;
use App\Http\Controllers\Apps\UserManagementController;
use App\Http\Controllers\Auth\SocialiteController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\Apps\SignaturePadController;
use Illuminate\Support\Facades\Route;
use \InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController;
use Symfony\Component\HttpFoundation\File\File;




/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/modules/{module}/{type}/{file}', [ function ($module, $type, $file) {

//     return 'aaaa';
// }]);

// Routes accessible only to users with "Super Admin" role
// Route::middleware(['auth', 'superAdmin'])->group(function () {
//     // Your protected routes go here
//     Route::get('/', function () {
//         return 'This is Super Admin';
//     });
// });

// Route::middleware(['auth', 'role:Super Admin'])->group(function () {
//     // Route::get('/', function () {
//     //     return 'This is Super Admin';
//     // });
//     Route::get('/', [DashboardController::class, 'index']);
//     Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
//     Route::resource('logs', App\Http\Controllers\LogController::class);
//     Route::resource('user-infos', App\Http\Controllers\UserInfoController::class);

//     Route::name('user-management.')->group(function () {
//         Route::resource('/user-management/users', UserManagementController::class);
//         Route::resource('/user-management/roles', RoleManagementController::class);
//         Route::resource('/user-management/permissions', PermissionManagementController::class);
//     });
// });

// Route::get('generator_builder', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@builder')->name('io_generator_builder');
// Route::get('generator_builder', [GeneratorBuilderController::class, 'builder'])->name('io_generator_builder');
// Route::get('field_template', [GeneratorBuilderController::class, 'fieldTemplate'])->name('io_field_template');
// Route::get('relation_field_template', [GeneratorBuilderController::class, 'relationFieldTemplate'])->name('io_relation_field_template');
// Route::post('generator_builder/generate', [GeneratorBuilderController::class, 'generate'])->name('io_generator_builder_generate');
// Route::post('generator_builder/generate-from-file', [GeneratorBuilderController::class, 'generateFromFile'])->name('io_generator_builder_generate_from_file');
// Route::post('generator_builder/rollback', [GeneratorBuilderController::class, 'rollback'])->name('io_generator_builder_rollback');

// Route::get('field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@fieldTemplate')->name('io_field_template');

// Route::get('relation_field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@relationFieldTemplate')->name('io_relation_field_template');

// Route::post('generator_builder/generate', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generate')->name('io_generator_builder_generate');

// Route::post('generator_builder/rollback', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@rollback')->name('io_generator_builder_rollback');

// ×Fail! The POST method is not supported for route generator_builder/generate. Supported methods: GET, HEAD.


// Route::post(
//     'generator_builder/generate-from-file',
//     '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generateFromFile'
// )->name('io_generator_builder_generate_from_file');


Route::middleware(['auth'])->group(function () {

    // Route::get('/', [DashboardController::class, 'index']);

    // Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::resource('logs', App\Http\Controllers\LogController::class);
    Route::resource('user-infos', App\Http\Controllers\UserInfoController::class);

    Route::name('user-management.')->group(function () {
        Route::get('/user-management/my-profile', [UserManagementController::class, 'myProfile'])->name('myProfile');
        Route::resource('/user-management/users', UserManagementController::class);
        Route::resource('/user-management/roles', RoleManagementController::class);
        Route::resource('/user-management/permissions', PermissionManagementController::class);

        // API
        Route::prefix('/user-management/api')->group(function () {
            Route::post('/users', [UserManagementController::class, 'saveUser'])->name('postUser');

        });
    });

    Route::name('apps.')->group(function () {
        Route::resource('/apps/signaturepad', SignaturePadController::class);

        // API
        // Route::prefix('/user-management/api')->group(function () {
        //     Route::post('/users', [UserManagementController::class, 'saveUser'])->name('postUser');

        // });
    });

    Route::name('settings.')->group(function () {
        Route::get('/settings', [SettingController::class, 'index'])->name('index');
        Route::get('/image/{disk}/{filename}', [SettingController::class, 'showLogo'])->name('showLogo');

        Route::get('/settings/company', [CompanyController::class, 'index'])->name('company');

        // Route::resource('company', CompanyController::class,[
        //     'as' => 'company'
        // ]);

        // API
        Route::prefix('/setting/api')->group(function () {
            Route::get('/company', [SettingController::class, 'getCompany'])->name('getCompany');
            Route::get('/limit', [SettingController::class, 'getLimit'])->name('getLimit');
            Route::get('/version', [SettingController::class, 'getVersion'])->name('getVersion');
            Route::post('/company', [SettingController::class, 'saveCompany'])->name('postCompany');
            Route::post('/sla', [SettingController::class, 'saveSla'])->name('postSla');
            Route::get('/notification', [SettingController::class, 'getNotification'])->name('getNotification');
            Route::post('/notification', [SettingController::class, 'saveNotification'])->name('postNotification');
            Route::put('/update-company-status/{id}', [SettingController::class, 'updateStatus'])->name('update-company-status');
            // Route::put('/update-company-status/{id}', 'SettingController@updateStatus')->name('update-company-status');
            // Route::post('/company', 'SettingController@saveCompany');

        });

    });

});



Route::get('/clear-cache/{cacheType?}', [SettingController::class, 'clearCache'])
                ->name('clear-cache');

Route::get('/error', function () {
    abort(500);
});

Route::get('/auth/redirect/{provider}', [SocialiteController::class, 'redirect']);

require __DIR__ . '/auth.php';
require __DIR__.'/superadmin.php';
require __DIR__.'/client.php';

// Fallback route
// Route::fallback(function () {
//     return redirect()->back();
// });




Route::resource('user-infos', App\Http\Controllers\UserInfoController::class);

app/Models/UserInfo.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class UserInfo extends Model
{
    public $table = 'user_info';

    protected $connection = 'mysql';

    public $fillable = [
        'user_id',
        'alamat',
        'telp',
        'wa'
    ];

    protected $casts = [
        'alamat' => 'string',
        'telp' => 'string',
        'wa' => 'string'
    ];

    public static array $rules = [
        'user_id' => 'required',
        'alamat' => 'required|string|max:191',
        'telp' => 'required|string|max:191',
        'wa' => 'required|string|max:191',
        'created_at' => 'nullable',
        'updated_at' => 'nullable'
    ];

    
}

app/Http/Controllers/UserInfoController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\UserInfoDataTable;
use App\Http\Requests\CreateUserInfoRequest;
use App\Http\Requests\UpdateUserInfoRequest;
use App\Http\Controllers\AppBaseController;
use App\Repositories\UserInfoRepository;
use Illuminate\Http\Request;
use Flash;

class UserInfoController extends AppBaseController
{
    /** @var UserInfoRepository $userInfoRepository*/
    private $userInfoRepository;

    public function __construct(UserInfoRepository $userInfoRepo)
    {
        $this->userInfoRepository = $userInfoRepo;
    }

    /**
     * Display a listing of the UserInfo.
     */
    public function index(UserInfoDataTable $userInfoDataTable)
    {
    return $userInfoDataTable->render('user_infos.index');
    }



    /**
     * Show the form for creating a new UserInfo.
     */
    public function create()
    {
        return view('user_infos.create');
    }

    /**
     * Store a newly created UserInfo in storage.
     */
    public function store(CreateUserInfoRequest $request)
    {
        $input = $request->all();

        $userInfo = $this->userInfoRepository->create($input);

        Flash::success('User Info saved successfully.');

        return redirect(route('userInfos.index'));
    }

    /**
     * Display the specified UserInfo.
     */
    public function show($id)
    {
        $userInfo = $this->userInfoRepository->find($id);

        if (empty($userInfo)) {
            Flash::error('User Info not found');

            return redirect(route('userInfos.index'));
        }

        return view('user_infos.show')->with('userInfo', $userInfo);
    }

    /**
     * Show the form for editing the specified UserInfo.
     */
    public function edit($id)
    {
        $userInfo = $this->userInfoRepository->find($id);

        if (empty($userInfo)) {
            Flash::error('User Info not found');

            return redirect(route('userInfos.index'));
        }

        return view('user_infos.edit')->with('userInfo', $userInfo);
    }

    /**
     * Update the specified UserInfo in storage.
     */
    public function update($id, UpdateUserInfoRequest $request)
    {
        $userInfo = $this->userInfoRepository->find($id);

        if (empty($userInfo)) {
            Flash::error('User Info not found');

            return redirect(route('userInfos.index'));
        }

        $userInfo = $this->userInfoRepository->update($request->all(), $id);

        Flash::success('User Info updated successfully.');

        return redirect(route('userInfos.index'));
    }

    /**
     * Remove the specified UserInfo from storage.
     *
     * @throws \Exception
     */
    public function destroy($id)
    {
        $userInfo = $this->userInfoRepository->find($id);

        if (empty($userInfo)) {
            Flash::error('User Info not found');

            return redirect(route('userInfos.index'));
        }

        $this->userInfoRepository->delete($id);

        Flash::success('User Info deleted successfully.');

        return redirect(route('userInfos.index'));
    }

    public function company()
    {
        return view('user_infos.company');
    }
}

app/View/Components/DefaultLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class DefaultLayout extends Component
{
    /**
     * Create a new component instance.
     *
     * @return void
     */
    public function __construct()
    {
        // Init layout file
        app(config('settings.KT_THEME_BOOTSTRAP.default'))->init();
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render()
    {
        // See also starterkit/app/Core/Bootstrap/BootstrapDefault.php
        return view(config('settings.KT_THEME_LAYOUT_DIR').'._default');
    }
}

resources/views/user_infos/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1>
                    Create User Infos
                    </h1>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('adminlte-templates::common.errors')

        <div class="card">

            {!! Form::open(['route' => 'userInfos.store']) !!}

            <div class="card-body">

                <div class="row">
                    @include('user_infos.fields')
                </div>

            </div>

            <div class="card-footer">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('userInfos.index') }}" class="btn btn-default"> Cancel </a>
            </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/user_infos/datatables_actions.blade.php
{!! Form::open(['route' => ['userInfos.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('userInfos.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="fa fa-eye"></i>
    </a>
    <a href="{{ route('userInfos.edit', $id) }}" class='btn btn-default btn-xs'>
        <i class="fa fa-edit"></i>
    </a>
    {!! Form::button('<i class="fa fa-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => 'return confirm("'.__('crud.are_you_sure').'")'

    ]) !!}
</div>
{!! Form::close() !!}

resources/views/user_infos/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-12">
                    <h1>
                        Edit User Info
                    </h1>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('adminlte-templates::common.errors')

        <div class="card">

            {!! Form::model($userInfo, ['route' => ['userInfos.update', $userInfo->id], 'method' => 'patch']) !!}

            <div class="card-body">
                <div class="row">
                    @include('user_infos.fields')
                </div>
            </div>

            <div class="card-footer">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('userInfos.index') }}" class="btn btn-default"> Cancel </a>
            </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/user_infos/fields.blade.php
<!-- User Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('user_id', 'User Id:') !!}
    {!! Form::number('user_id', null, ['class' => 'form-control', 'required']) !!}
</div>

<!-- Alamat Field -->
<div class="form-group col-sm-6">
    {!! Form::label('alamat', 'Alamat:') !!}
    {!! Form::text('alamat', null, ['class' => 'form-control', 'required', 'maxlength' => 191, 'maxlength' => 191]) !!}
</div>

<!-- Telp Field -->
<div class="form-group col-sm-6">
    {!! Form::label('telp', 'Telp:') !!}
    {!! Form::text('telp', null, ['class' => 'form-control', 'required', 'maxlength' => 191, 'maxlength' => 191]) !!}
</div>

<!-- Wa Field -->
<div class="form-group col-sm-6">
    {!! Form::label('wa', 'Wa:') !!}
    {!! Form::text('wa', null, ['class' => 'form-control', 'required', 'maxlength' => 191, 'maxlength' => 191]) !!}
</div>

resources/views/user_infos/index.blade.php
<x-default-layout>
@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>User Info</h1>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">

        @include('flash::message')

        <div class="clearfix"></div>

        <div class="card">
            @include('user_infos.table')
        </div>
    </div>

    </x-default-layout>

resources/views/user_infos/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>
User Info Details
                    </h1>
                </div>
                <div class="col-sm-6">
                    <a class="btn btn-default float-right"
                       href="{{ route('userInfos.index') }}">
                                                    Back
                                            </a>
                </div>
            </div>
        </div>
    </section>

    <div class="content px-3">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    @include('user_infos.show_fields')
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/user_infos/show_fields.blade.php
<!-- User Id Field -->
<div class="col-sm-12">
    {!! Form::label('user_id', 'User Id:') !!}
    <p>{{ $userInfo->user_id }}</p>
</div>

<!-- Alamat Field -->
<div class="col-sm-12">
    {!! Form::label('alamat', 'Alamat:') !!}
    <p>{{ $userInfo->alamat }}</p>
</div>

<!-- Telp Field -->
<div class="col-sm-12">
    {!! Form::label('telp', 'Telp:') !!}
    <p>{{ $userInfo->telp }}</p>
</div>

<!-- Wa Field -->
<div class="col-sm-12">
    {!! Form::label('wa', 'Wa:') !!}
    <p>{{ $userInfo->wa }}</p>
</div>

resources/views/user_infos/table.blade.php
@push('styles')
    @include('layouts.datatables_css')

<style>
.wrap {
    word-wrap: break-word;
}
</style>
@endpush

<div class="card-body px-4">
    {!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered']) !!}
</div>

@push('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endpush